Load the Dataset & Handle Missing Values

In [ ]:
import pandas as pd
import numpy as np
# Load dataset
df = pd.read_csv("/content/sample_data/winequality-red.csv", delimiter=';')
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [ ]:
#Check missing values
df.isnull().sum()
#Replace null values with column mean
df = df.fillna(df.mean())

Extract Columns as Vectors: alcohol and citric acid

In [ ]:
alcohol_vector = df['alcohol'].values
citric_acid_vector = df['citric acid'].values

print(alcohol_vector[:5])
print(citric_acid_vector[:5])

[9.4 9.8 9.8 9.8 9.4]
[0.   0.   0.04 0.56 0.  ]

Covariance Matrix of Selected Features

In [ ]:
X = df[['alcohol', 'density']].values

cov_matrix = np.cov(X.T)
cov_matrix

array([[ 1.13564740e+00, -9.97951790e-04],
       [-9.97951790e-04,  3.56202945e-06]])

Eigen Decomposition of Covariance Matrix

In [ ]:
#Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
eigenvalues, eigenvectors

(array([1.13564827e+00, 2.68507580e-06]),
 array([[ 9.99999614e-01,  8.78753184e-04],
        [-8.78753184e-04,  9.99999614e-01]]))

In [ ]:
#Identify top 2 eigenvalues
sorted_indices = np.argsort(eigenvalues)[::-1]
top_eigenvalues = eigenvalues[sorted_indices]
top_eigenvectors = eigenvectors[:, sorted_indices]

top_eigenvalues, top_eigenvectors

(array([1.13564827e+00, 2.68507580e-06]),
 array([[ 9.99999614e-01,  8.78753184e-04],
        [-8.78753184e-04,  9.99999614e-01]]))

Most Common Wine Quality & Distribution Interpretation

In [ ]:
quality_counts = df['quality'].value_counts()
quality_counts

quality
5    681
6    638
7    199
4     53
8     18
3     10
Name: count, dtype: int64

In [ ]:
most_common_quality = quality_counts.idxmax()
most_common_quality

np.int64(5)

The most common wine quality score is 5 or 6.

Distribution shows:
Most wines are average quality.
Very few wines are extremely low or high quality.
This indicates a normal-like distribution, centered around mid-range quality